<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Platforms>x64</Platforms>
    <TargetFramework>net48</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\..\Assets\Icon.ico" Link="Assets\Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WixToolset.BootstrapperApplicationApi" Version="7.*" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\ShellView.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

</Project>
